title: Blockchain Career Day
description: > # this means to ignore newlines until "baseurl:"
  The Blockchain Career Day takes place on June 2 at Garage Society in Wan Chai, organized by the Bitcoin Association of Hong Kong.
baseurl: "" # the subpath of your site, e.g. /blog
url: "cryptocareer.hk" # the base hostname & protocol for your site
image: "../css/2019_style/img/og.png"
# Build settings
markdown: kramdown
lang: en_HK

# Social
logo: "../css/2017_style/img/icon-large.png"

twitter:
  username: bitcoinorghk
  card: summary

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages', '_2019_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/bitcoinorghk
  - title: twitter
    url: https://twitter.com/bitcoinorghk
  - title: instagram
    url: https://www.instagram.com/bitcoinorghk/
  - title: linkedin
    url: https://www.linkedin.com/company/the-bitcoin-association-of-hong-kong/

# Build settings
markdown: kramdown
permalink: pretty
